server {
  listen 80;
  server_name i1off.nomorepartiessite.ru api.i1off.nomorepartiessite.ru;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 200 'ok';
  }
}

### Для первого запуска nginx нужно создать домен в Nginx и в Let's Encrypt